/* Generated By:JavaCC: Do not edit this line. HitAssAstParserConstants.java */
package org.poormanscastle.products.hit2ass.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HitAssAstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOU_OPENER = 1;
  /** RegularExpression Id. */
  int END_COMMENT = 7;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int ENDIF = 12;
  /** RegularExpression Id. */
  int SB = 13;
  /** RegularExpression Id. */
  int WS = 14;
  /** RegularExpression Id. */
  int FS = 15;
  /** RegularExpression Id. */
  int SS = 16;
  /** RegularExpression Id. */
  int CA = 17;
  /** RegularExpression Id. */
  int MS = 18;
  /** RegularExpression Id. */
  int HC = 19;
  /** RegularExpression Id. */
  int GS = 20;
  /** RegularExpression Id. */
  int JS = 21;
  /** RegularExpression Id. */
  int ZS = 22;
  /** RegularExpression Id. */
  int GD = 23;
  /** RegularExpression Id. */
  int LD = 24;
  /** RegularExpression Id. */
  int LIST = 25;
  /** RegularExpression Id. */
  int DUMP = 26;
  /** RegularExpression Id. */
  int AS = 27;
  /** RegularExpression Id. */
  int IB = 28;
  /** RegularExpression Id. */
  int OF = 29;
  /** RegularExpression Id. */
  int DV = 30;
  /** RegularExpression Id. */
  int PS = 31;
  /** RegularExpression Id. */
  int SK = 32;
  /** RegularExpression Id. */
  int FIXED_TEXT = 33;
  /** RegularExpression Id. */
  int DV_ID = 38;
  /** RegularExpression Id. */
  int FILE_OPEN = 43;
  /** RegularExpression Id. */
  int FILE_CLOSE = 44;
  /** RegularExpression Id. */
  int FILE_READ = 45;
  /** RegularExpression Id. */
  int FILE_TEXT = 46;
  /** RegularExpression Id. */
  int IB_TEXT = 51;
  /** RegularExpression Id. */
  int PS_SB = 60;
  /** RegularExpression Id. */
  int PS_LBRACKET = 61;
  /** RegularExpression Id. */
  int PS_RBRACKET = 62;
  /** RegularExpression Id. */
  int PS_ID = 63;
  /** RegularExpression Id. */
  int SS_SHELLVAR = 68;
  /** RegularExpression Id. */
  int SS_LPAREN = 69;
  /** RegularExpression Id. */
  int SS_RPAREN = 70;
  /** RegularExpression Id. */
  int SS_QUOTE = 71;
  /** RegularExpression Id. */
  int SS_SHELLVAR_ID = 72;
  /** RegularExpression Id. */
  int SS_COMMA = 73;
  /** RegularExpression Id. */
  int SS_LBRACKET = 74;
  /** RegularExpression Id. */
  int SS_RBRACKET = 75;
  /** RegularExpression Id. */
  int SS_NUM = 76;
  /** RegularExpression Id. */
  int SS_ID = 77;
  /** RegularExpression Id. */
  int CA_COLON = 78;
  /** RegularExpression Id. */
  int SK_VAR_ID = 79;
  /** RegularExpression Id. */
  int MS_EQ = 88;
  /** RegularExpression Id. */
  int MS_EQ_STRICT = 89;
  /** RegularExpression Id. */
  int MS_OR = 90;
  /** RegularExpression Id. */
  int MS_AND = 91;
  /** RegularExpression Id. */
  int MS_XOR = 92;
  /** RegularExpression Id. */
  int MS_NOT = 93;
  /** RegularExpression Id. */
  int MS_NEQ = 94;
  /** RegularExpression Id. */
  int MS_LT = 95;
  /** RegularExpression Id. */
  int MS_LTE = 96;
  /** RegularExpression Id. */
  int MS_GT = 97;
  /** RegularExpression Id. */
  int MS_GTE = 98;
  /** RegularExpression Id. */
  int MS_PLUS = 99;
  /** RegularExpression Id. */
  int MS_MINUS = 100;
  /** RegularExpression Id. */
  int MS_TIMES = 101;
  /** RegularExpression Id. */
  int MS_DIV = 102;
  /** RegularExpression Id. */
  int MS_LPAREN = 103;
  /** RegularExpression Id. */
  int MS_RPAREN = 104;
  /** RegularExpression Id. */
  int MS_LBRACKET = 105;
  /** RegularExpression Id. */
  int MS_RBRACKET = 106;
  /** RegularExpression Id. */
  int MS_COMMA = 107;
  /** RegularExpression Id. */
  int MS_NUM = 108;
  /** RegularExpression Id. */
  int MS_DEC = 109;
  /** RegularExpression Id. */
  int MS_ID = 110;
  /** RegularExpression Id. */
  int MS_TEXT = 111;
  /** RegularExpression Id. */
  int IF_SHELLVAR = 112;
  /** RegularExpression Id. */
  int IF_EQ = 113;
  /** RegularExpression Id. */
  int IF_EQ_STRICT = 114;
  /** RegularExpression Id. */
  int IF_OR = 115;
  /** RegularExpression Id. */
  int IF_AND = 116;
  /** RegularExpression Id. */
  int IF_XOR = 117;
  /** RegularExpression Id. */
  int IF_NOT = 118;
  /** RegularExpression Id. */
  int IF_NEQ = 119;
  /** RegularExpression Id. */
  int IF_LT = 120;
  /** RegularExpression Id. */
  int IF_LTE = 121;
  /** RegularExpression Id. */
  int IF_GT = 122;
  /** RegularExpression Id. */
  int IF_GTE = 123;
  /** RegularExpression Id. */
  int IF_PLUS = 124;
  /** RegularExpression Id. */
  int IF_MINUS = 125;
  /** RegularExpression Id. */
  int IF_TIMES = 126;
  /** RegularExpression Id. */
  int IF_DIV = 127;
  /** RegularExpression Id. */
  int IF_QUOTE = 128;
  /** RegularExpression Id. */
  int IF_COLON = 129;
  /** RegularExpression Id. */
  int IF_LPAREN = 130;
  /** RegularExpression Id. */
  int IF_RPAREN = 131;
  /** RegularExpression Id. */
  int IF_NUM = 132;
  /** RegularExpression Id. */
  int IF_LBRACKET = 133;
  /** RegularExpression Id. */
  int IF_RBRACKET = 134;
  /** RegularExpression Id. */
  int IF_DEC = 135;
  /** RegularExpression Id. */
  int IF_SHELLVAR_ID = 136;
  /** RegularExpression Id. */
  int IF_ID = 137;
  /** RegularExpression Id. */
  int IF_TEXT = 138;
  /** RegularExpression Id. */
  int FOR_SHELLVAR = 143;
  /** RegularExpression Id. */
  int FOR_EQ = 144;
  /** RegularExpression Id. */
  int FOR_EQ_STRICT = 145;
  /** RegularExpression Id. */
  int FOR_OR = 146;
  /** RegularExpression Id. */
  int FOR_AND = 147;
  /** RegularExpression Id. */
  int FOR_XOR = 148;
  /** RegularExpression Id. */
  int FOR_NOT = 149;
  /** RegularExpression Id. */
  int FOR_NEQ = 150;
  /** RegularExpression Id. */
  int FOR_LT = 151;
  /** RegularExpression Id. */
  int FOR_LTE = 152;
  /** RegularExpression Id. */
  int FOR_GT = 153;
  /** RegularExpression Id. */
  int FOR_GTE = 154;
  /** RegularExpression Id. */
  int FOR_PLUS = 155;
  /** RegularExpression Id. */
  int FOR_MINUS = 156;
  /** RegularExpression Id. */
  int FOR_TIMES = 157;
  /** RegularExpression Id. */
  int FOR_DIV = 158;
  /** RegularExpression Id. */
  int FOR_QUOTE = 159;
  /** RegularExpression Id. */
  int FOR_COLON = 160;
  /** RegularExpression Id. */
  int FOR_LPAREN = 161;
  /** RegularExpression Id. */
  int FOR_RPAREN = 162;
  /** RegularExpression Id. */
  int FOR_NUM = 163;
  /** RegularExpression Id. */
  int FOR_LBRACKET = 164;
  /** RegularExpression Id. */
  int FOR_RBRACKET = 165;
  /** RegularExpression Id. */
  int FOR_DEC = 166;
  /** RegularExpression Id. */
  int FOR_SHELLVAR_ID = 167;
  /** RegularExpression Id. */
  int FOR_ID = 168;
  /** RegularExpression Id. */
  int FOR_TEXT = 169;
  /** RegularExpression Id. */
  int DS_EQ = 174;
  /** RegularExpression Id. */
  int DS_EQ_STRICT = 175;
  /** RegularExpression Id. */
  int DS_OR = 176;
  /** RegularExpression Id. */
  int DS_AND = 177;
  /** RegularExpression Id. */
  int DS_XOR = 178;
  /** RegularExpression Id. */
  int DS_NOT = 179;
  /** RegularExpression Id. */
  int DS_NEQ = 180;
  /** RegularExpression Id. */
  int DS_LT = 181;
  /** RegularExpression Id. */
  int DS_LTE = 182;
  /** RegularExpression Id. */
  int DS_GT = 183;
  /** RegularExpression Id. */
  int DS_GTE = 184;
  /** RegularExpression Id. */
  int DS_STRING_CONCAT = 185;
  /** RegularExpression Id. */
  int DS_PLUS = 186;
  /** RegularExpression Id. */
  int DS_MINUS = 187;
  /** RegularExpression Id. */
  int DS_TIMES = 188;
  /** RegularExpression Id. */
  int DS_DIV = 189;
  /** RegularExpression Id. */
  int DS_QUOTE = 190;
  /** RegularExpression Id. */
  int DS_COLON = 191;
  /** RegularExpression Id. */
  int DS_LPAREN = 192;
  /** RegularExpression Id. */
  int DS_RPAREN = 193;
  /** RegularExpression Id. */
  int DS_LBRACKET = 194;
  /** RegularExpression Id. */
  int DS_RBRACKET = 195;
  /** RegularExpression Id. */
  int DS_NUM = 196;
  /** RegularExpression Id. */
  int DS_DEC = 197;
  /** RegularExpression Id. */
  int DS_ID = 198;
  /** RegularExpression Id. */
  int DS_TEXT = 199;
  /** RegularExpression Id. */
  int AS_SHELLVAR = 204;
  /** RegularExpression Id. */
  int AS_EQ = 205;
  /** RegularExpression Id. */
  int AS_EQ_STRICT = 206;
  /** RegularExpression Id. */
  int AS_OR = 207;
  /** RegularExpression Id. */
  int AS_AND = 208;
  /** RegularExpression Id. */
  int AS_XOR = 209;
  /** RegularExpression Id. */
  int AS_NOT = 210;
  /** RegularExpression Id. */
  int AS_NEQ = 211;
  /** RegularExpression Id. */
  int AS_LT = 212;
  /** RegularExpression Id. */
  int AS_LTE = 213;
  /** RegularExpression Id. */
  int AS_GT = 214;
  /** RegularExpression Id. */
  int AS_GTE = 215;
  /** RegularExpression Id. */
  int AS_COMMA = 216;
  /** RegularExpression Id. */
  int AS_STRING_CONCAT = 217;
  /** RegularExpression Id. */
  int AS_PLUS = 218;
  /** RegularExpression Id. */
  int AS_MINUS = 219;
  /** RegularExpression Id. */
  int AS_TIMES = 220;
  /** RegularExpression Id. */
  int AS_DIV = 221;
  /** RegularExpression Id. */
  int AS_QUOTE = 222;
  /** RegularExpression Id. */
  int AS_COLON = 223;
  /** RegularExpression Id. */
  int AS_LPAREN = 224;
  /** RegularExpression Id. */
  int AS_RPAREN = 225;
  /** RegularExpression Id. */
  int AS_LBRACKET = 226;
  /** RegularExpression Id. */
  int AS_RBRACKET = 227;
  /** RegularExpression Id. */
  int AS_NUM = 228;
  /** RegularExpression Id. */
  int AS_DEC = 229;
  /** RegularExpression Id. */
  int AS_SHELLVAR_ID = 230;
  /** RegularExpression Id. */
  int AS_ID = 231;
  /** RegularExpression Id. */
  int AS_TEXT = 232;
  /** RegularExpression Id. */
  int LS_AMPERSAND = 237;
  /** RegularExpression Id. */
  int LS_LBRACE = 238;
  /** RegularExpression Id. */
  int LS_GD = 239;
  /** RegularExpression Id. */
  int LS_LD = 240;
  /** RegularExpression Id. */
  int LS_LBRACKET = 241;
  /** RegularExpression Id. */
  int LS_RBRACKET = 242;
  /** RegularExpression Id. */
  int LS_ID = 243;
  /** RegularExpression Id. */
  int LS_TEXT = 244;
  /** RegularExpression Id. */
  int DUMP_TEXT = 253;
  /** RegularExpression Id. */
  int LS_BRACES_AMPERSAND = 254;
  /** RegularExpression Id. */
  int LS_BRACES_COMMA = 255;
  /** RegularExpression Id. */
  int LS_BRACES_RBRACE = 256;
  /** RegularExpression Id. */
  int LS_BRACES_LBRACKET = 257;
  /** RegularExpression Id. */
  int LS_BRACES_RBRACKET = 258;
  /** RegularExpression Id. */
  int LS_BRACES_NUM = 259;
  /** RegularExpression Id. */
  int LS_BRACES_DEC = 260;
  /** RegularExpression Id. */
  int LS_BRACES_ID = 261;
  /** RegularExpression Id. */
  int LS_BRACES_TEXT = 262;
  /** RegularExpression Id. */
  int HC_HC = 267;
  /** RegularExpression Id. */
  int HC_NUM = 268;
  /** RegularExpression Id. */
  int HC_LBRACKET = 269;
  /** RegularExpression Id. */
  int HC_RBRACKET = 270;
  /** RegularExpression Id. */
  int HC_ID = 271;
  /** RegularExpression Id. */
  int HC_NAME = 272;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TXT_MODE = 1;
  /** Lexical state. */
  int COMMAND_MODE_DS = 2;
  /** Lexical state. */
  int COMMAND_MODE_SS = 3;
  /** Lexical state. */
  int COMMAND_MODE_AS = 4;
  /** Lexical state. */
  int COMMAND_MODE_MS = 5;
  /** Lexical state. */
  int COMMENT_MODE = 6;
  /** Lexical state. */
  int COMMAND_MODE_DV = 7;
  /** Lexical state. */
  int COMMAND_MODE_FILE = 8;
  /** Lexical state. */
  int COMMAND_MODE_IB = 9;
  /** Lexical state. */
  int COMMAND_MODE_PS = 10;
  /** Lexical state. */
  int COMMAND_MODE_SK = 11;
  /** Lexical state. */
  int COMMAND_MODE_IF = 12;
  /** Lexical state. */
  int COMMAND_MODE_FOR = 13;
  /** Lexical state. */
  int COMMAND_MODE_LS = 14;
  /** Lexical state. */
  int COMMAND_MODE_DUMP = 15;
  /** Lexical state. */
  int COMMAND_MODE_LS_BRACES = 16;
  /** Lexical state. */
  int COMMAND_MODE_HC = 17;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CLOU_OPENER>",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#\"",
    "<token of kind 8>",
    "\"#?\"",
    "\"/J\"",
    "\"/N\"",
    "\"#\"",
    "\"@\"",
    "\"#S\"",
    "\"#W\"",
    "\"#C\"",
    "<CA>",
    "\"#$\"",
    "\"#^\"",
    "\"#G\"",
    "\"#J\"",
    "\"#Z\"",
    "\"#D\"",
    "\"#d\"",
    "\"#L\"",
    "\"#q\"",
    "\"#=\"",
    "\"#B\"",
    "\"#X\"",
    "<DV>",
    "\"#>\"",
    "\"#!\"",
    "<FIXED_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<DV_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"O\"",
    "\"C\"",
    "\"\\\"r\\\"\"",
    "<FILE_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<IB_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "<PS_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<SS_SHELLVAR_ID>",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<SS_NUM>",
    "<SS_ID>",
    "\":\"",
    "<SK_VAR_ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<MS_NUM>",
    "<MS_DEC>",
    "<MS_ID>",
    "<MS_TEXT>",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<IF_NUM>",
    "\"[\"",
    "\"]\"",
    "<IF_DEC>",
    "<IF_SHELLVAR_ID>",
    "<IF_ID>",
    "<IF_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<FOR_NUM>",
    "\"[\"",
    "\"]\"",
    "<FOR_DEC>",
    "<FOR_SHELLVAR_ID>",
    "<FOR_ID>",
    "<FOR_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<DS_NUM>",
    "<DS_DEC>",
    "<DS_ID>",
    "<DS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<AS_NUM>",
    "<AS_DEC>",
    "<AS_SHELLVAR_ID>",
    "<AS_ID>",
    "<AS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"&\"",
    "\"{\"",
    "\"D\"",
    "\"d\"",
    "\"[\"",
    "\"]\"",
    "<LS_ID>",
    "<LS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<DUMP_TEXT>",
    "\"&\"",
    "\",\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<LS_BRACES_NUM>",
    "<LS_BRACES_DEC>",
    "<LS_BRACES_ID>",
    "<LS_BRACES_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"#^\"",
    "<HC_NUM>",
    "\"[\"",
    "\"]\"",
    "<HC_ID>",
    "<HC_NAME>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
  };

}
