/* Generated By:JavaCC: Do not edit this line. HitAssAstParserConstants.java */
package org.poormanscastle.products.hit2ass.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HitAssAstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOU_OPENER = 1;
  /** RegularExpression Id. */
  int END_COMMENT = 7;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int ENDIF = 12;
  /** RegularExpression Id. */
  int WS = 13;
  /** RegularExpression Id. */
  int SS = 14;
  /** RegularExpression Id. */
  int CA = 15;
  /** RegularExpression Id. */
  int MS = 16;
  /** RegularExpression Id. */
  int HC = 17;
  /** RegularExpression Id. */
  int GS = 18;
  /** RegularExpression Id. */
  int JS = 19;
  /** RegularExpression Id. */
  int ZS = 20;
  /** RegularExpression Id. */
  int GD = 21;
  /** RegularExpression Id. */
  int LD = 22;
  /** RegularExpression Id. */
  int LIST = 23;
  /** RegularExpression Id. */
  int DUMP = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int IB = 26;
  /** RegularExpression Id. */
  int OF = 27;
  /** RegularExpression Id. */
  int DV = 28;
  /** RegularExpression Id. */
  int PS = 29;
  /** RegularExpression Id. */
  int SK = 30;
  /** RegularExpression Id. */
  int FIXED_TEXT = 31;
  /** RegularExpression Id. */
  int DV_ID = 36;
  /** RegularExpression Id. */
  int FILE_OPEN = 41;
  /** RegularExpression Id. */
  int FILE_CLOSE = 42;
  /** RegularExpression Id. */
  int FILE_READ = 43;
  /** RegularExpression Id. */
  int FILE_TEXT = 44;
  /** RegularExpression Id. */
  int IB_TEXT = 49;
  /** RegularExpression Id. */
  int PS_ID = 58;
  /** RegularExpression Id. */
  int SS_SHELLVAR = 63;
  /** RegularExpression Id. */
  int SS_LPAREN = 64;
  /** RegularExpression Id. */
  int SS_RPAREN = 65;
  /** RegularExpression Id. */
  int SS_QUOTE = 66;
  /** RegularExpression Id. */
  int SS_SHELLVAR_ID = 67;
  /** RegularExpression Id. */
  int SS_COMMA = 68;
  /** RegularExpression Id. */
  int SS_LBRACKET = 69;
  /** RegularExpression Id. */
  int SS_RBRACKET = 70;
  /** RegularExpression Id. */
  int SS_NUM = 71;
  /** RegularExpression Id. */
  int SS_ID = 72;
  /** RegularExpression Id. */
  int CA_COLON = 73;
  /** RegularExpression Id. */
  int SK_VAR_ID = 74;
  /** RegularExpression Id. */
  int MS_EQ = 83;
  /** RegularExpression Id. */
  int MS_EQ_STRICT = 84;
  /** RegularExpression Id. */
  int MS_OR = 85;
  /** RegularExpression Id. */
  int MS_AND = 86;
  /** RegularExpression Id. */
  int MS_XOR = 87;
  /** RegularExpression Id. */
  int MS_NOT = 88;
  /** RegularExpression Id. */
  int MS_NEQ = 89;
  /** RegularExpression Id. */
  int MS_LT = 90;
  /** RegularExpression Id. */
  int MS_LTE = 91;
  /** RegularExpression Id. */
  int MS_GT = 92;
  /** RegularExpression Id. */
  int MS_GTE = 93;
  /** RegularExpression Id. */
  int MS_PLUS = 94;
  /** RegularExpression Id. */
  int MS_MINUS = 95;
  /** RegularExpression Id. */
  int MS_TIMES = 96;
  /** RegularExpression Id. */
  int MS_DIV = 97;
  /** RegularExpression Id. */
  int MS_LPAREN = 98;
  /** RegularExpression Id. */
  int MS_RPAREN = 99;
  /** RegularExpression Id. */
  int MS_COMMA = 100;
  /** RegularExpression Id. */
  int MS_NUM = 101;
  /** RegularExpression Id. */
  int MS_DEC = 102;
  /** RegularExpression Id. */
  int MS_ID = 103;
  /** RegularExpression Id. */
  int MS_TEXT = 104;
  /** RegularExpression Id. */
  int IF_SHELLVAR = 105;
  /** RegularExpression Id. */
  int IF_EQ = 106;
  /** RegularExpression Id. */
  int IF_EQ_STRICT = 107;
  /** RegularExpression Id. */
  int IF_OR = 108;
  /** RegularExpression Id. */
  int IF_AND = 109;
  /** RegularExpression Id. */
  int IF_XOR = 110;
  /** RegularExpression Id. */
  int IF_NOT = 111;
  /** RegularExpression Id. */
  int IF_NEQ = 112;
  /** RegularExpression Id. */
  int IF_LT = 113;
  /** RegularExpression Id. */
  int IF_LTE = 114;
  /** RegularExpression Id. */
  int IF_GT = 115;
  /** RegularExpression Id. */
  int IF_GTE = 116;
  /** RegularExpression Id. */
  int IF_PLUS = 117;
  /** RegularExpression Id. */
  int IF_MINUS = 118;
  /** RegularExpression Id. */
  int IF_TIMES = 119;
  /** RegularExpression Id. */
  int IF_DIV = 120;
  /** RegularExpression Id. */
  int IF_QUOTE = 121;
  /** RegularExpression Id. */
  int IF_COLON = 122;
  /** RegularExpression Id. */
  int IF_LPAREN = 123;
  /** RegularExpression Id. */
  int IF_RPAREN = 124;
  /** RegularExpression Id. */
  int IF_NUM = 125;
  /** RegularExpression Id. */
  int IF_LBRACKET = 126;
  /** RegularExpression Id. */
  int IF_RBRACKET = 127;
  /** RegularExpression Id. */
  int IF_DEC = 128;
  /** RegularExpression Id. */
  int IF_SHELLVAR_ID = 129;
  /** RegularExpression Id. */
  int IF_ID = 130;
  /** RegularExpression Id. */
  int IF_TEXT = 131;
  /** RegularExpression Id. */
  int DS_EQ = 136;
  /** RegularExpression Id. */
  int DS_EQ_STRICT = 137;
  /** RegularExpression Id. */
  int DS_OR = 138;
  /** RegularExpression Id. */
  int DS_AND = 139;
  /** RegularExpression Id. */
  int DS_XOR = 140;
  /** RegularExpression Id. */
  int DS_NOT = 141;
  /** RegularExpression Id. */
  int DS_NEQ = 142;
  /** RegularExpression Id. */
  int DS_LT = 143;
  /** RegularExpression Id. */
  int DS_LTE = 144;
  /** RegularExpression Id. */
  int DS_GT = 145;
  /** RegularExpression Id. */
  int DS_GTE = 146;
  /** RegularExpression Id. */
  int DS_STRING_CONCAT = 147;
  /** RegularExpression Id. */
  int DS_PLUS = 148;
  /** RegularExpression Id. */
  int DS_MINUS = 149;
  /** RegularExpression Id. */
  int DS_TIMES = 150;
  /** RegularExpression Id. */
  int DS_DIV = 151;
  /** RegularExpression Id. */
  int DS_QUOTE = 152;
  /** RegularExpression Id. */
  int DS_COLON = 153;
  /** RegularExpression Id. */
  int DS_LPAREN = 154;
  /** RegularExpression Id. */
  int DS_RPAREN = 155;
  /** RegularExpression Id. */
  int DS_NUM = 156;
  /** RegularExpression Id. */
  int DS_DEC = 157;
  /** RegularExpression Id. */
  int DS_ID = 158;
  /** RegularExpression Id. */
  int DS_TEXT = 159;
  /** RegularExpression Id. */
  int AS_SHELLVAR = 164;
  /** RegularExpression Id. */
  int AS_EQ = 165;
  /** RegularExpression Id. */
  int AS_EQ_STRICT = 166;
  /** RegularExpression Id. */
  int AS_OR = 167;
  /** RegularExpression Id. */
  int AS_AND = 168;
  /** RegularExpression Id. */
  int AS_XOR = 169;
  /** RegularExpression Id. */
  int AS_NOT = 170;
  /** RegularExpression Id. */
  int AS_NEQ = 171;
  /** RegularExpression Id. */
  int AS_LT = 172;
  /** RegularExpression Id. */
  int AS_LTE = 173;
  /** RegularExpression Id. */
  int AS_GT = 174;
  /** RegularExpression Id. */
  int AS_GTE = 175;
  /** RegularExpression Id. */
  int AS_COMMA = 176;
  /** RegularExpression Id. */
  int AS_STRING_CONCAT = 177;
  /** RegularExpression Id. */
  int AS_PLUS = 178;
  /** RegularExpression Id. */
  int AS_MINUS = 179;
  /** RegularExpression Id. */
  int AS_TIMES = 180;
  /** RegularExpression Id. */
  int AS_DIV = 181;
  /** RegularExpression Id. */
  int AS_QUOTE = 182;
  /** RegularExpression Id. */
  int AS_COLON = 183;
  /** RegularExpression Id. */
  int AS_LPAREN = 184;
  /** RegularExpression Id. */
  int AS_RPAREN = 185;
  /** RegularExpression Id. */
  int AS_LBRACKET = 186;
  /** RegularExpression Id. */
  int AS_RBRACKET = 187;
  /** RegularExpression Id. */
  int AS_NUM = 188;
  /** RegularExpression Id. */
  int AS_DEC = 189;
  /** RegularExpression Id. */
  int AS_SHELLVAR_ID = 190;
  /** RegularExpression Id. */
  int AS_ID = 191;
  /** RegularExpression Id. */
  int AS_TEXT = 192;
  /** RegularExpression Id. */
  int LS_AMPERSAND = 197;
  /** RegularExpression Id. */
  int LS_LBRACE = 198;
  /** RegularExpression Id. */
  int LS_GD = 199;
  /** RegularExpression Id. */
  int LS_LD = 200;
  /** RegularExpression Id. */
  int LS_ID = 201;
  /** RegularExpression Id. */
  int LS_TEXT = 202;
  /** RegularExpression Id. */
  int DUMP_TEXT = 211;
  /** RegularExpression Id. */
  int LS_BRACES_AMPERSAND = 212;
  /** RegularExpression Id. */
  int LS_BRACES_COMMA = 213;
  /** RegularExpression Id. */
  int LS_BRACES_RBRACE = 214;
  /** RegularExpression Id. */
  int LS_BRACES_NUM = 215;
  /** RegularExpression Id. */
  int LS_BRACES_DEC = 216;
  /** RegularExpression Id. */
  int LS_BRACES_ID = 217;
  /** RegularExpression Id. */
  int LS_BRACES_TEXT = 218;
  /** RegularExpression Id. */
  int HC_HC = 223;
  /** RegularExpression Id. */
  int HC_NUM = 224;
  /** RegularExpression Id. */
  int HC_ID = 225;
  /** RegularExpression Id. */
  int HC_NAME = 226;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TXT_MODE = 1;
  /** Lexical state. */
  int COMMAND_MODE_DS = 2;
  /** Lexical state. */
  int COMMAND_MODE_SS = 3;
  /** Lexical state. */
  int COMMAND_MODE_AS = 4;
  /** Lexical state. */
  int COMMAND_MODE_MS = 5;
  /** Lexical state. */
  int COMMENT_MODE = 6;
  /** Lexical state. */
  int COMMAND_MODE_DV = 7;
  /** Lexical state. */
  int COMMAND_MODE_FILE = 8;
  /** Lexical state. */
  int COMMAND_MODE_IB = 9;
  /** Lexical state. */
  int COMMAND_MODE_PS = 10;
  /** Lexical state. */
  int COMMAND_MODE_SK = 11;
  /** Lexical state. */
  int COMMAND_MODE_IF = 12;
  /** Lexical state. */
  int COMMAND_MODE_LS = 13;
  /** Lexical state. */
  int COMMAND_MODE_DUMP = 14;
  /** Lexical state. */
  int COMMAND_MODE_LS_BRACES = 15;
  /** Lexical state. */
  int COMMAND_MODE_HC = 16;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CLOU_OPENER>",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#\"",
    "<token of kind 8>",
    "\"#?\"",
    "\"/J\"",
    "\"/N\"",
    "\"#\"",
    "\"#S\"",
    "\"#C\"",
    "<CA>",
    "\"#$\"",
    "\"#^\"",
    "\"#G\"",
    "\"#J\"",
    "\"#Z\"",
    "\"#D\"",
    "\"#d\"",
    "\"#L\"",
    "\"#q\"",
    "\"#=\"",
    "\"#B\"",
    "\"#X\"",
    "<DV>",
    "\"#>\"",
    "\"#!\"",
    "<FIXED_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<DV_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"O\"",
    "\"C\"",
    "\"\\\"r\\\"\"",
    "<FILE_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<IB_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<PS_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<SS_SHELLVAR_ID>",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<SS_NUM>",
    "<SS_ID>",
    "\":\"",
    "<SK_VAR_ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<MS_NUM>",
    "<MS_DEC>",
    "<MS_ID>",
    "<MS_TEXT>",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<IF_NUM>",
    "\"[\"",
    "\"]\"",
    "<IF_DEC>",
    "<IF_SHELLVAR_ID>",
    "<IF_ID>",
    "<IF_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<DS_NUM>",
    "<DS_DEC>",
    "<DS_ID>",
    "<DS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<AS_NUM>",
    "<AS_DEC>",
    "<AS_SHELLVAR_ID>",
    "<AS_ID>",
    "<AS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"&\"",
    "\"{\"",
    "\"D\"",
    "\"d\"",
    "<LS_ID>",
    "<LS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<DUMP_TEXT>",
    "\"&\"",
    "\",\"",
    "\"}\"",
    "<LS_BRACES_NUM>",
    "<LS_BRACES_DEC>",
    "<LS_BRACES_ID>",
    "<LS_BRACES_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"#^\"",
    "<HC_NUM>",
    "<HC_ID>",
    "<HC_NAME>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
  };

}
