/* Generated By:JavaCC: Do not edit this line. HitAssAstParserConstants.java */
package org.poormanscastle.products.hit2ass.parser.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HitAssAstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLOU_OPENER = 1;
  /** RegularExpression Id. */
  int END_COMMENT = 7;
  /** RegularExpression Id. */
  int IF = 9;
  /** RegularExpression Id. */
  int THEN = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int ENDIF = 12;
  /** RegularExpression Id. */
  int SB = 13;
  /** RegularExpression Id. */
  int WS = 14;
  /** RegularExpression Id. */
  int FS = 15;
  /** RegularExpression Id. */
  int SS = 16;
  /** RegularExpression Id. */
  int CA = 17;
  /** RegularExpression Id. */
  int MS = 18;
  /** RegularExpression Id. */
  int HC = 19;
  /** RegularExpression Id. */
  int GS = 20;
  /** RegularExpression Id. */
  int JS = 21;
  /** RegularExpression Id. */
  int ZS = 22;
  /** RegularExpression Id. */
  int GD = 23;
  /** RegularExpression Id. */
  int LD = 24;
  /** RegularExpression Id. */
  int LIST = 25;
  /** RegularExpression Id. */
  int DUMP = 26;
  /** RegularExpression Id. */
  int AS = 27;
  /** RegularExpression Id. */
  int IB = 28;
  /** RegularExpression Id. */
  int OF = 29;
  /** RegularExpression Id. */
  int DV = 30;
  /** RegularExpression Id. */
  int PS = 31;
  /** RegularExpression Id. */
  int SK = 32;
  /** RegularExpression Id. */
  int FIXED_TEXT = 33;
  /** RegularExpression Id. */
  int DV_ID = 38;
  /** RegularExpression Id. */
  int FILE_OPEN = 43;
  /** RegularExpression Id. */
  int FILE_CLOSE = 44;
  /** RegularExpression Id. */
  int FILE_READ = 45;
  /** RegularExpression Id. */
  int FILE_TEXT = 46;
  /** RegularExpression Id. */
  int IB_TEXT = 51;
  /** RegularExpression Id. */
  int PS_SB = 60;
  /** RegularExpression Id. */
  int PS_EQ = 61;
  /** RegularExpression Id. */
  int PS_EQ_STRICT = 62;
  /** RegularExpression Id. */
  int PS_OR = 63;
  /** RegularExpression Id. */
  int PS_AND = 64;
  /** RegularExpression Id. */
  int PS_XOR = 65;
  /** RegularExpression Id. */
  int PS_NOT = 66;
  /** RegularExpression Id. */
  int PS_NEQ = 67;
  /** RegularExpression Id. */
  int PS_LT = 68;
  /** RegularExpression Id. */
  int PS_LTE = 69;
  /** RegularExpression Id. */
  int PS_GT = 70;
  /** RegularExpression Id. */
  int PS_GTE = 71;
  /** RegularExpression Id. */
  int PS_PLUS = 72;
  /** RegularExpression Id. */
  int PS_MINUS = 73;
  /** RegularExpression Id. */
  int PS_TIMES = 74;
  /** RegularExpression Id. */
  int PS_DIV = 75;
  /** RegularExpression Id. */
  int PS_QUOTE = 76;
  /** RegularExpression Id. */
  int PS_LPAREN = 77;
  /** RegularExpression Id. */
  int PS_RPAREN = 78;
  /** RegularExpression Id. */
  int PS_NUM = 79;
  /** RegularExpression Id. */
  int PS_DEC = 80;
  /** RegularExpression Id. */
  int PS_ID = 81;
  /** RegularExpression Id. */
  int PS_IDX_CHECK_LBRACKET = 82;
  /** RegularExpression Id. */
  int PS_IDX_CHECK_FIXED_TEXT = 83;
  /** RegularExpression Id. */
  int PS_IDX_SB = 84;
  /** RegularExpression Id. */
  int PS_IDX_CHECK_SKIP = 85;
  /** RegularExpression Id. */
  int PS_IDX_LBRACKET = 90;
  /** RegularExpression Id. */
  int PS_IDX_RBRACKET = 91;
  /** RegularExpression Id. */
  int PS_IDX_EQ = 92;
  /** RegularExpression Id. */
  int PS_IDX_EQ_STRICT = 93;
  /** RegularExpression Id. */
  int PS_IDX_OR = 94;
  /** RegularExpression Id. */
  int PS_IDX_AND = 95;
  /** RegularExpression Id. */
  int PS_IDX_XOR = 96;
  /** RegularExpression Id. */
  int PS_IDX_NOT = 97;
  /** RegularExpression Id. */
  int PS_IDX_NEQ = 98;
  /** RegularExpression Id. */
  int PS_IDX_LT = 99;
  /** RegularExpression Id. */
  int PS_IDX_LTE = 100;
  /** RegularExpression Id. */
  int PS_IDX_GT = 101;
  /** RegularExpression Id. */
  int PS_IDX_GTE = 102;
  /** RegularExpression Id. */
  int PS_IDX_PLUS = 103;
  /** RegularExpression Id. */
  int PS_IDX_MINUS = 104;
  /** RegularExpression Id. */
  int PS_IDX_TIMES = 105;
  /** RegularExpression Id. */
  int PS_IDX_DIV = 106;
  /** RegularExpression Id. */
  int PS_IDX_QUOTE = 107;
  /** RegularExpression Id. */
  int PS_IDX_LPAREN = 108;
  /** RegularExpression Id. */
  int PS_IDX_RPAREN = 109;
  /** RegularExpression Id. */
  int PS_IDX_COMMA = 110;
  /** RegularExpression Id. */
  int PS_IDX_NUM = 111;
  /** RegularExpression Id. */
  int PS_IDX_DEC = 112;
  /** RegularExpression Id. */
  int PS_IDX_ID = 113;
  /** RegularExpression Id. */
  int SS_SHELLVAR = 118;
  /** RegularExpression Id. */
  int SS_LPAREN = 119;
  /** RegularExpression Id. */
  int SS_RPAREN = 120;
  /** RegularExpression Id. */
  int SS_QUOTE = 121;
  /** RegularExpression Id. */
  int SS_SHELLVAR_ID = 122;
  /** RegularExpression Id. */
  int SS_COMMA = 123;
  /** RegularExpression Id. */
  int SS_LBRACKET = 124;
  /** RegularExpression Id. */
  int SS_RBRACKET = 125;
  /** RegularExpression Id. */
  int SS_NUM = 126;
  /** RegularExpression Id. */
  int SS_ID = 127;
  /** RegularExpression Id. */
  int CA_COLON = 128;
  /** RegularExpression Id. */
  int SK_VAR_ID = 129;
  /** RegularExpression Id. */
  int MS_EQ = 138;
  /** RegularExpression Id. */
  int MS_EQ_STRICT = 139;
  /** RegularExpression Id. */
  int MS_OR = 140;
  /** RegularExpression Id. */
  int MS_AND = 141;
  /** RegularExpression Id. */
  int MS_XOR = 142;
  /** RegularExpression Id. */
  int MS_NOT = 143;
  /** RegularExpression Id. */
  int MS_NEQ = 144;
  /** RegularExpression Id. */
  int MS_LT = 145;
  /** RegularExpression Id. */
  int MS_LTE = 146;
  /** RegularExpression Id. */
  int MS_GT = 147;
  /** RegularExpression Id. */
  int MS_GTE = 148;
  /** RegularExpression Id. */
  int MS_PLUS = 149;
  /** RegularExpression Id. */
  int MS_MINUS = 150;
  /** RegularExpression Id. */
  int MS_TIMES = 151;
  /** RegularExpression Id. */
  int MS_DIV = 152;
  /** RegularExpression Id. */
  int MS_LPAREN = 153;
  /** RegularExpression Id. */
  int MS_RPAREN = 154;
  /** RegularExpression Id. */
  int MS_LBRACKET = 155;
  /** RegularExpression Id. */
  int MS_RBRACKET = 156;
  /** RegularExpression Id. */
  int MS_COMMA = 157;
  /** RegularExpression Id. */
  int MS_NUM = 158;
  /** RegularExpression Id. */
  int MS_DEC = 159;
  /** RegularExpression Id. */
  int MS_ID = 160;
  /** RegularExpression Id. */
  int MS_TEXT = 161;
  /** RegularExpression Id. */
  int IF_SHELLVAR = 162;
  /** RegularExpression Id. */
  int IF_EQ = 163;
  /** RegularExpression Id. */
  int IF_EQ_STRICT = 164;
  /** RegularExpression Id. */
  int IF_OR = 165;
  /** RegularExpression Id. */
  int IF_AND = 166;
  /** RegularExpression Id. */
  int IF_XOR = 167;
  /** RegularExpression Id. */
  int IF_NOT = 168;
  /** RegularExpression Id. */
  int IF_NEQ = 169;
  /** RegularExpression Id. */
  int IF_LT = 170;
  /** RegularExpression Id. */
  int IF_LTE = 171;
  /** RegularExpression Id. */
  int IF_GT = 172;
  /** RegularExpression Id. */
  int IF_GTE = 173;
  /** RegularExpression Id. */
  int IF_PLUS = 174;
  /** RegularExpression Id. */
  int IF_MINUS = 175;
  /** RegularExpression Id. */
  int IF_TIMES = 176;
  /** RegularExpression Id. */
  int IF_DIV = 177;
  /** RegularExpression Id. */
  int IF_QUOTE = 178;
  /** RegularExpression Id. */
  int IF_COLON = 179;
  /** RegularExpression Id. */
  int IF_LPAREN = 180;
  /** RegularExpression Id. */
  int IF_RPAREN = 181;
  /** RegularExpression Id. */
  int IF_NUM = 182;
  /** RegularExpression Id. */
  int IF_LBRACKET = 183;
  /** RegularExpression Id. */
  int IF_RBRACKET = 184;
  /** RegularExpression Id. */
  int IF_DEC = 185;
  /** RegularExpression Id. */
  int IF_SHELLVAR_ID = 186;
  /** RegularExpression Id. */
  int IF_ID = 187;
  /** RegularExpression Id. */
  int IF_TEXT = 188;
  /** RegularExpression Id. */
  int FOR_SHELLVAR = 193;
  /** RegularExpression Id. */
  int FOR_EQ = 194;
  /** RegularExpression Id. */
  int FOR_EQ_STRICT = 195;
  /** RegularExpression Id. */
  int FOR_OR = 196;
  /** RegularExpression Id. */
  int FOR_AND = 197;
  /** RegularExpression Id. */
  int FOR_XOR = 198;
  /** RegularExpression Id. */
  int FOR_NOT = 199;
  /** RegularExpression Id. */
  int FOR_NEQ = 200;
  /** RegularExpression Id. */
  int FOR_LT = 201;
  /** RegularExpression Id. */
  int FOR_LTE = 202;
  /** RegularExpression Id. */
  int FOR_GT = 203;
  /** RegularExpression Id. */
  int FOR_GTE = 204;
  /** RegularExpression Id. */
  int FOR_PLUS = 205;
  /** RegularExpression Id. */
  int FOR_MINUS = 206;
  /** RegularExpression Id. */
  int FOR_TIMES = 207;
  /** RegularExpression Id. */
  int FOR_DIV = 208;
  /** RegularExpression Id. */
  int FOR_QUOTE = 209;
  /** RegularExpression Id. */
  int FOR_COLON = 210;
  /** RegularExpression Id. */
  int FOR_LPAREN = 211;
  /** RegularExpression Id. */
  int FOR_RPAREN = 212;
  /** RegularExpression Id. */
  int FOR_NUM = 213;
  /** RegularExpression Id. */
  int FOR_LBRACKET = 214;
  /** RegularExpression Id. */
  int FOR_RBRACKET = 215;
  /** RegularExpression Id. */
  int FOR_DEC = 216;
  /** RegularExpression Id. */
  int FOR_SHELLVAR_ID = 217;
  /** RegularExpression Id. */
  int FOR_ID = 218;
  /** RegularExpression Id. */
  int FOR_TEXT = 219;
  /** RegularExpression Id. */
  int DS_EQ = 224;
  /** RegularExpression Id. */
  int DS_EQ_STRICT = 225;
  /** RegularExpression Id. */
  int DS_OR = 226;
  /** RegularExpression Id. */
  int DS_AND = 227;
  /** RegularExpression Id. */
  int DS_XOR = 228;
  /** RegularExpression Id. */
  int DS_NOT = 229;
  /** RegularExpression Id. */
  int DS_NEQ = 230;
  /** RegularExpression Id. */
  int DS_LT = 231;
  /** RegularExpression Id. */
  int DS_LTE = 232;
  /** RegularExpression Id. */
  int DS_GT = 233;
  /** RegularExpression Id. */
  int DS_GTE = 234;
  /** RegularExpression Id. */
  int DS_STRING_CONCAT = 235;
  /** RegularExpression Id. */
  int DS_PLUS = 236;
  /** RegularExpression Id. */
  int DS_MINUS = 237;
  /** RegularExpression Id. */
  int DS_TIMES = 238;
  /** RegularExpression Id. */
  int DS_DIV = 239;
  /** RegularExpression Id. */
  int DS_QUOTE = 240;
  /** RegularExpression Id. */
  int DS_COLON = 241;
  /** RegularExpression Id. */
  int DS_COMMA = 242;
  /** RegularExpression Id. */
  int DS_LPAREN = 243;
  /** RegularExpression Id. */
  int DS_RPAREN = 244;
  /** RegularExpression Id. */
  int DS_LBRACKET = 245;
  /** RegularExpression Id. */
  int DS_RBRACKET = 246;
  /** RegularExpression Id. */
  int DS_NUM = 247;
  /** RegularExpression Id. */
  int DS_DEC = 248;
  /** RegularExpression Id. */
  int DS_ID = 249;
  /** RegularExpression Id. */
  int DS_TEXT = 250;
  /** RegularExpression Id. */
  int AS_SHELLVAR = 255;
  /** RegularExpression Id. */
  int AS_SB = 256;
  /** RegularExpression Id. */
  int AS_EQ = 257;
  /** RegularExpression Id. */
  int AS_EQ_STRICT = 258;
  /** RegularExpression Id. */
  int AS_OR = 259;
  /** RegularExpression Id. */
  int AS_AND = 260;
  /** RegularExpression Id. */
  int AS_XOR = 261;
  /** RegularExpression Id. */
  int AS_NOT = 262;
  /** RegularExpression Id. */
  int AS_NEQ = 263;
  /** RegularExpression Id. */
  int AS_LT = 264;
  /** RegularExpression Id. */
  int AS_LTE = 265;
  /** RegularExpression Id. */
  int AS_GT = 266;
  /** RegularExpression Id. */
  int AS_GTE = 267;
  /** RegularExpression Id. */
  int AS_COMMA = 268;
  /** RegularExpression Id. */
  int AS_STRING_CONCAT = 269;
  /** RegularExpression Id. */
  int AS_PLUS = 270;
  /** RegularExpression Id. */
  int AS_MINUS = 271;
  /** RegularExpression Id. */
  int AS_TIMES = 272;
  /** RegularExpression Id. */
  int AS_DIV = 273;
  /** RegularExpression Id. */
  int AS_QUOTE = 274;
  /** RegularExpression Id. */
  int AS_COLON = 275;
  /** RegularExpression Id. */
  int AS_LPAREN = 276;
  /** RegularExpression Id. */
  int AS_RPAREN = 277;
  /** RegularExpression Id. */
  int AS_LBRACKET = 278;
  /** RegularExpression Id. */
  int AS_RBRACKET = 279;
  /** RegularExpression Id. */
  int AS_NUM = 280;
  /** RegularExpression Id. */
  int AS_DEC = 281;
  /** RegularExpression Id. */
  int AS_SHELLVAR_ID = 282;
  /** RegularExpression Id. */
  int AS_ID = 283;
  /** RegularExpression Id. */
  int AS_TEXT = 284;
  /** RegularExpression Id. */
  int LS_AMPERSAND = 289;
  /** RegularExpression Id. */
  int LS_LBRACE = 290;
  /** RegularExpression Id. */
  int LS_GD = 291;
  /** RegularExpression Id. */
  int LS_LD = 292;
  /** RegularExpression Id. */
  int LS_LBRACKET = 293;
  /** RegularExpression Id. */
  int LS_RBRACKET = 294;
  /** RegularExpression Id. */
  int LS_ID = 295;
  /** RegularExpression Id. */
  int LS_TEXT = 296;
  /** RegularExpression Id. */
  int DUMP_TEXT = 305;
  /** RegularExpression Id. */
  int LS_BRACES_AMPERSAND = 306;
  /** RegularExpression Id. */
  int LS_BRACES_COMMA = 307;
  /** RegularExpression Id. */
  int LS_BRACES_RBRACE = 308;
  /** RegularExpression Id. */
  int LS_BRACES_LBRACKET = 309;
  /** RegularExpression Id. */
  int LS_BRACES_RBRACKET = 310;
  /** RegularExpression Id. */
  int LS_BRACES_NUM = 311;
  /** RegularExpression Id. */
  int LS_BRACES_DEC = 312;
  /** RegularExpression Id. */
  int LS_BRACES_ID = 313;
  /** RegularExpression Id. */
  int LS_BRACES_TEXT = 314;
  /** RegularExpression Id. */
  int HC_HC = 319;
  /** RegularExpression Id. */
  int HC_NUM = 320;
  /** RegularExpression Id. */
  int HC_LBRACKET = 321;
  /** RegularExpression Id. */
  int HC_RBRACKET = 322;
  /** RegularExpression Id. */
  int HC_ID = 323;
  /** RegularExpression Id. */
  int HC_NAME = 324;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TXT_MODE = 1;
  /** Lexical state. */
  int COMMAND_MODE_DS = 2;
  /** Lexical state. */
  int COMMAND_MODE_SS = 3;
  /** Lexical state. */
  int COMMAND_MODE_AS = 4;
  /** Lexical state. */
  int COMMAND_MODE_MS = 5;
  /** Lexical state. */
  int COMMENT_MODE = 6;
  /** Lexical state. */
  int COMMAND_MODE_DV = 7;
  /** Lexical state. */
  int COMMAND_MODE_FILE = 8;
  /** Lexical state. */
  int COMMAND_MODE_IB = 9;
  /** Lexical state. */
  int COMMAND_MODE_PS = 10;
  /** Lexical state. */
  int COMMAND_MODE_PS_IDX_CHECK = 11;
  /** Lexical state. */
  int COMMAND_MODE_PS_IDX = 12;
  /** Lexical state. */
  int COMMAND_MODE_SK = 13;
  /** Lexical state. */
  int COMMAND_MODE_IF = 14;
  /** Lexical state. */
  int COMMAND_MODE_FOR = 15;
  /** Lexical state. */
  int COMMAND_MODE_LS = 16;
  /** Lexical state. */
  int COMMAND_MODE_DUMP = 17;
  /** Lexical state. */
  int COMMAND_MODE_LS_BRACES = 18;
  /** Lexical state. */
  int COMMAND_MODE_HC = 19;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<CLOU_OPENER>",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#*\"",
    "\"#\"",
    "<token of kind 8>",
    "\"#?\"",
    "\"/J\"",
    "\"/N\"",
    "\"#\"",
    "\"@\"",
    "\"#S\"",
    "\"#W\"",
    "\"#C\"",
    "<CA>",
    "\"#$\"",
    "\"#^\"",
    "\"#G\"",
    "\"#J\"",
    "\"#Z\"",
    "\"#D\"",
    "\"#d\"",
    "\"#L\"",
    "\"#q\"",
    "\"#=\"",
    "\"#B\"",
    "\"#X\"",
    "<DV>",
    "\"#>\"",
    "\"#!\"",
    "<FIXED_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<DV_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"O\"",
    "\"C\"",
    "\"\\\"r\\\"\"",
    "<FILE_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "<IB_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"@\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "<PS_NUM>",
    "<PS_DEC>",
    "<PS_ID>",
    "\"[\"",
    "<PS_IDX_CHECK_FIXED_TEXT>",
    "\"@\"",
    "<PS_IDX_CHECK_SKIP>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"[\"",
    "\"]\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<PS_IDX_NUM>",
    "<PS_IDX_DEC>",
    "<PS_IDX_ID>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"(\"",
    "\")\"",
    "\"\\\"\"",
    "<SS_SHELLVAR_ID>",
    "\",\"",
    "\"[\"",
    "\"]\"",
    "<SS_NUM>",
    "<SS_ID>",
    "\":\"",
    "<SK_VAR_ID>",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "<MS_NUM>",
    "<MS_DEC>",
    "<MS_ID>",
    "<MS_TEXT>",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<IF_NUM>",
    "\"[\"",
    "\"]\"",
    "<IF_DEC>",
    "<IF_SHELLVAR_ID>",
    "<IF_ID>",
    "<IF_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "<FOR_NUM>",
    "\"[\"",
    "\"]\"",
    "<FOR_DEC>",
    "<FOR_SHELLVAR_ID>",
    "<FOR_ID>",
    "<FOR_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<DS_NUM>",
    "<DS_DEC>",
    "<DS_ID>",
    "<DS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"SHELLVARIABLE\"",
    "\"@\"",
    "\"=\"",
    "\"==\"",
    "\"oder\"",
    "\"und\"",
    "\"xor_tbd\"",
    "\"not_tbd\"",
    "\"<>\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\",\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"\\\"\"",
    "\":\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "<AS_NUM>",
    "<AS_DEC>",
    "<AS_SHELLVAR_ID>",
    "<AS_ID>",
    "<AS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"&\"",
    "\"{\"",
    "\"D\"",
    "\"d\"",
    "\"[\"",
    "\"]\"",
    "<LS_ID>",
    "<LS_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\" \"",
    "\"\\t\"",
    "<DUMP_TEXT>",
    "\"&\"",
    "\",\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<LS_BRACES_NUM>",
    "<LS_BRACES_DEC>",
    "<LS_BRACES_ID>",
    "<LS_BRACES_TEXT>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
    "\"#^\"",
    "<HC_NUM>",
    "\"[\"",
    "\"]\"",
    "<HC_ID>",
    "<HC_NAME>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\" \"",
  };

}
